luku1_str = input(" anna luku 1: ")
luku2_str = input(" anna luku 2: ")
luku3_str = input(" anna luku 3: ")
luku1 = float(luku1_str)
luku2 = float(luku2_str)
luku3 = float(luku3_str)
summa = (luku1+luku2+luku3)
tulo = (luku1*luku2*luku3)
keskiarvo = (luku1+luku2+luku3)/3
print(" lukujen summa: " + str(summa))
print(" lukujen tulo: " + str(tulo))
print(" lukujen keskiarvo: " + str(keskiarvo))
